DROP TABLE IF EXISTS "Bookmarks";
DROP TABLE IF EXISTS "Chapters";
DROP TABLE IF EXISTS "Books";
DROP TABLE IF EXISTS "Files";
DROP TABLE IF EXISTS "Users";
DROP TABLE IF EXISTS "__EFMigrationsHistory";